### ISSUE TITLE
Clean pull ne dela

### ISSUE THREAD

**Issue by MitjaR** [andrejborstnik/track-collector#4]
Začetni del informacij o napaki:

/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/browser-sync/lib/browser-sync.js:544
    bs.debug("Setting Option: {cyan:%s} - {magenta:%s", name, value.toString());
                                                                   ^

TypeError: Cannot read property 'toString' of undefined

**Comment by andrejborstnik** [comment]
Je @mihic isto sporočil. Ampak jaz ne morem reproducirat.

**Comment by MitjaR** [comment]
Sedaj javi drugje napako:

[11:33:34] Starting 'split-bundler-vendor'...
[11:33:34] 'split-bundler-vendor' errored after 183 μs
[11:33:34] Error: ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.readFileSync (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/jsonfile/index.js:66:20)
    at Gulp.<anonymous> (/home/mitja/Documents/GoOpti/track-collector/frontend/gulpfile.babel.js:560:33)
    at module.exports (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:75:5)
[11:33:34] Error in plugin 'run-sequence(split-bundler-vendor)'
Message:
    ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: build/.cache/dependencies.json
Stack:
Error: ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.readFileSync (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/jsonfile/index.js:66:20)
    at Gulp.<anonymous> (/home/mitja/Documents/GoOpti/track-collector/frontend/gulpfile.babel.js:560:33)
    at module.exports (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:75:5)
[11:33:34] Error in plugin 'run-sequence(split-bundler-vendor)'
Message:
    ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: build/.cache/dependencies.json
Stack:
Error: ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.readFileSync (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/jsonfile/index.js:66:20)
    at Gulp.<anonymous> (/home/mitja/Documents/GoOpti/track-collector/frontend/gulpfile.babel.js:560:33)
    at module.exports (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:75:5)
[11:33:34] Error in plugin 'run-sequence(split-bundler-vendor)'
Message:
    ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: build/.cache/dependencies.json
Stack:
Error: ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.readFileSync (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/jsonfile/index.js:66:20)
    at Gulp.<anonymous> (/home/mitja/Documents/GoOpti/track-collector/frontend/gulpfile.babel.js:560:33)
    at module.exports (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:75:5)
[11:33:34] Error in plugin 'run-sequence(split-bundler-vendor)'
Message:
    ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: build/.cache/dependencies.json
Stack:
Error: ENOENT: no such file or directory, open 'build/.cache/dependencies.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.readFileSync (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/jsonfile/index.js:66:20)
    at Gulp.<anonymous> (/home/mitja/Documents/GoOpti/track-collector/frontend/gulpfile.babel.js:560:33)
    at module.exports (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/home/mitja/Documents/GoOpti/track-collector/frontend/node_modules/run-sequence/index.js:75:5)
[11:33:34] Finished 'split-bundler' after 33 ms
[11:33:34] Finished 'app-scripts' after 33 ms
[11:33:34] Finished 'frontend-build' after 33 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GPS@ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GPS@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mitja/.npm/_logs/2017-07-12T09_33_34_306Z-debug.log

**Comment by MitjaR** [comment]
Tole manjka, mogoče veš kako bi popravil:

'build/.cache/dependencies.json'

**Comment by andrejborstnik** [comment]
Naredi prazen file (mogoče mora imeti {} notri) s tem imenom tam.

**Comment by andrejborstnik** [comment]
Iz readme:
Podobno velja za datoteko '../../local.config', ki izgleda npr. takole (na serverju). Pri sebi si raje nastavite fe_path na '/':
{
        "java_be": "https://test.goopti.com",
        "be_path": "/tracker",
        "url": "https://test.goopti.com",
        "fe_path": "/trackcollector",
        "be_port": "3102",
        "fe_port": "3002"
}

**Comment by MitjaR** [comment]
Ja dela, super.

**Comment by MitjaR** [comment]
Mislim moraš dat prazen json file v:

track-collector/frontend/build/.cache

Tam ustvariš prazen json file:

dependencies.json

Vsebina fila je samo:
{}
